name: SpeedPro
favicon: null
layout_spectrum: 0.9171980221290141
typography_spectrum: 0.9568751258775592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#ed2228'
    - '#393939'
    - '#7c7c7c'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
