name: SpeedPro
favicon: null
layout_spectrum: 0.9171980221290141
typography_spectrum: 0.9568751258775592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4994917658623308
  lightness: 0.9093104470521212
  saturation: 0.8481091866269708
  rhythmicContrast: 0.47070854157209396
purpose: []
